SELECT CPS.NAME_OF_SCHOOL, CPS.AVERAGE_STUDENT_ATTENDANCE, CD.COMMUNITY_AREA_NAME, CD.HARDSHIP_INDEX
FROM CHICAGO_PUBLIC_SCHOOLS AS CPS 
LEFT OUTER JOIN CENSUS_DATA AS CD
ON CPS.COMMUNITY_AREA_NUMBER = CD.COMMUNITY_AREA_NUMBER
AND CD.HARDSHIP_INDEX = 98;