SELECT CCD.CASE_NUMBER, CCD.PRIMARY_TYPE, CCD.LOCATION_DESCRIPTION, CD.COMMUNITY_AREA_NAME
FROM CHICAGO_CRIME_DATA AS CCD
LEFT OUTER JOIN CENSUS_DATA AS CD
ON CCD.COMMUNITY_AREA_NUMBER = CD.COMMUNITY_AREA_NUMBER
WHERE CCD.LOCATION_DESCRIPTION LIKE '%SCHOOL%';