--#SET TERMINATOR @

CREATE OR REPLACE PROCEDURE UPDATE_LEADERS_SCORE(
IN in_School_ID INTEGER,
IN in_Leader_Score INTEGER)

LANGUAGE SQL
MODIFIES SQL DATA


BEGIN

	UPDATE CHICAGO_PUBLIC_SCHOOLS
	SET Leaders_Score = in_Leader_Score
	WHERE School_ID = in_School_ID;

END

@